
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 20 15:00:26 BRT 2019
//----------------------------------------------------

package AnaliseSintatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int fimdelinha = 14;
  public static final int declaravari = 8;
  public static final int entrada = 7;
  public static final int relaciona = 11;
  public static final int operaciona = 12;
  public static final int p_int = 24;
  public static final int valor = 13;
  public static final int algoritmo = 2;
  public static final int doispontos = 29;
  public static final int saida = 22;
  public static final int faca = 19;
  public static final int repita = 23;
  public static final int senao = 20;
  public static final int inicio = 3;
  public static final int entao = 17;
  public static final int igual = 27;
  public static final int EOF = 0;
  public static final int abrepar = 9;
  public static final int fechapar = 10;
  public static final int error = 1;
  public static final int atribui = 6;
  public static final int virgula = 28;
  public static final int enquanto = 18;
  public static final int fim = 4;
  public static final int var = 5;
  public static final int pontofinal = 15;
  public static final int p_real = 26;
  public static final int p_str = 25;
  public static final int ate = 21;
  public static final int se = 16;
}

